### ISSUE TITLE
Create a Memcached CR" section (as per instruction deployment "example-memcached " didnt get created, but I can see pod example-memcached-pod running though

### ISSUE THREAD

**Issue by anravi** [operator-framework/getting-started#70] opened 2020-02-11 02:58 UTC
Create a Memcached CR" section (as per instruction deployment "example-memcached " didnt get created, but I can see pod example-memcached-pod running though
$ kubectl get deployment
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
memcached-operator   1/1     1            1           18m

can someone look into it?

_Originally posted by @anravi in https://github.com/operator-framework/getting-started/issues/64#issuecomment-584458626_

**Comment by camilamacedo86** [comment] 2020-02-11 03:01
Closing it as a duplicate of https://github.com/operator-framework/getting-started/issues/64

**Closed by camilamacedo86** 2020-02-11 03:01 UTC
