### ISSUE TITLE
The getting-started / OLM section is completely outdated and missleading.

### ISSUE THREAD

**Issue by mangelajo** [operator-framework/getting-started#55] opened 2019-10-16 07:32 UTC
https://github.com/operator-framework/getting-started#deploy-the-operator

CRD, SA, roles ... are now created by the OLM as far as I understand.

**Comment by camilamacedo86** [comment] 2019-10-16 08:39
It is true. I will get this one and as soon as possible we will be able to update it. 
Thank you for raise it.

**Comment by joelanford** [comment] 2019-10-17 14:55
@ecordell @dmesser With the recent docs focus from OLM, is there a plan to go through these existing repos and update them?

@camilamacedo86 let's see what plans the OLM folks have before working this. It may already be something they're planning to cover, and their expertise will probably be required anyway.

**Comment by camilamacedo86** [comment] 2019-10-17 17:53
Hi @joelanford,
 
OK. Just to share. The main problem that I could check as the root cause is CSV example file linked to it.
The steps to how to test locally, do the bundle and etc are described in https://github.com/operator-framework/community-operators#before-submitting-a-pr and we can address the users to check it.

**Comment by camilamacedo86** [comment] 2019-11-05 18:18
The OLM steps in the Getting Started as its example was updated in the #57 in order to address this issue as well. Then, I am closing this task. However, please, feel free to re-open if you see that still required.

**Closed by camilamacedo86** 2019-11-05 18:18 UTC
Labels: kind/bug, kind/documentation
