### ISSUE TITLE
error validating "memcachedoperator.0.0.1.csv.yaml"; unknown field "installModes" and unknown field "provider"

### ISSUE THREAD

**Issue by sjbylo** [operator-framework/getting-started#45] opened 2019-08-26 05:00 UTC
I'm seeing this error.  If I use --validate=false does not help. 

$ kubectl apply -f memcachedoperator.0.0.1.csv.yaml
error: error validating "memcachedoperator.0.0.1.csv.yaml": error validating data: [ValidationError(ClusterServiceVersion.spec): unknown field "installModes" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec, ValidationError(ClusterServiceVersion.spec): unknown field "provider" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by joelanford** [comment] 2019-09-03 13:12
@sjbylo This is sounds like an issue with your CSV or OLM installation. Can you provide more details? It would be helpful to know the version of OLM and/or the OpenShift cluster and the contents of `memcachedoperator.0.0.1.csv.yaml`. You may need re-create this issue in the OLM repository since OLM provides the API and validations for CSVs.

/cc @ecordell 

Did you use `operator-sdk olm-catalog gen-csv` to generate the CSV? If so, it would be also be helpful to know the output of `operator-sdk version` and the steps we could follow to reproduce the issue.

**Comment by joelanford** [comment] 2019-09-03 13:23
@sjbylo I am not able to reproduce the issue with the latest version of OLM. What version of OLM and/or OpenShift are you running?

**Comment by camilamacedo86** [comment] 2019-11-05 18:20
HI @joelanford, 

I understanding that it was faced because of the example file used was outdated. However, since the OLM steps in the Getting Started as its example was updated in the #57 then, I am closing this task. However, please, feel free to re-open if you see that still required.

**Closed by camilamacedo86** 2019-11-05 18:20 UTC
Labels: triage/not-reproducible, triage/support
