### ISSUE TITLE
Create a Memcached CR

### ISSUE THREAD

**Issue by oscarpicasso-intact** [operator-framework/getting-started#32] opened 2018-12-30 15:56 UTC
I followed the guide with no issue until section [Create a Memcached CR](https://github.com/operator-framework/getting-started#create-a-memcached-cr). Then I executed 
```
kubectl apply -f deploy/crds/cache_v1alpha1_memcached_cr.yaml
```

The example-memcached object is created in the namespace however no new deployments and pods are created.

**Comment by Michkov** [comment] 2019-07-27 18:47
Having same issue, log from operator:
```
E0727 18:12:00.305813       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:default:memcached-operator" cannot list resource "deployments" in API group "apps" at the cluster scope
E0727 18:12:00.305995       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *v1alpha1.Memcached: memcacheds.cache.example.com is forbidden: User "system:serviceaccount:default:memcached-operator" cannot list resource "memcacheds" in API group "cache.example.com" at the cluster scope

```

**Comment by takara9** [comment] 2019-08-16 07:03
I have same issue too.

$ kubectl apply -f deploy/crds/cache_v1alpha1_memcached_cr.yaml
memcached.cache.example.com/example-memcached created

$ kubectl get deploy
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
memcached-operator   1         1         1            1           8m

$ kubectl get -f deploy/crds/cache_v1alpha1_memcached_cr.yaml
NAME                AGE
example-memcached   17s

**Comment by camilamacedo86** [comment] 2019-09-04 15:09
Hi @Michkov , @takara9 and @oscarpicasso-intact,

Shows that the roles were not applied in the cluster. Note that the following files need to be applied to it. 

```
$ kubectl create -f deploy/role.yaml
$ kubectl create -f deploy/role_binding.yaml
``` 

Also, note that to be able to do this action successfully you need be logged in as a user with cluster privileges like the `system:admin` user. I this way, for example, you can be logged as admin by running the command `oc login -u system:admin.`

**Comment by camilamacedo86** [comment] 2019-09-04 16:35
Dear, 

We did a few improvements in the getting started in order to provide more information to help you with. Please, feel free to check it https://github.com/operator-framework/getting-started/pull/46.

**Comment by skckadiyala** [comment] 2019-09-06 22:07
I have the same issue...
followed the getting started guide..
$ kubectl create -f deploy/service_account.yaml
serviceaccount/memcached-operator created

$ kubectl create -f deploy/role.yaml
role.rbac.authorization.k8s.io/memcached-operator created

kubectl create -f deploy/role_binding.yaml
rolebinding.rbac.authorization.k8s.io/memcached-operator created

kubectl apply -f deploy/crds/cache_v1alpha1_memcached_cr.yaml
memcached.cache.systest.net/example-memcached created

$ kubectl get deployments
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
memcached-operator   1/1     1            1           4m11s

No new deployments are pods created for the example-memchaced.

**Comment by camilamacedo86** [comment] 2019-09-07 07:31
Hi @skckadiyala,

Could you please follow the changes performed in the PR https://github.com/operator-framework/getting-started/blob/11c5ccca3dd8231c465cc87b075c32a077690af6/README.md?

Note that you need:

1. Create the project 
2. Add the API + controller
3. Build the operator image and push it for your repo
4. Update the deploy/operator.yaml to use your image
( Note that it should be accessible to be pulled from your cluster ) 
5. Apply Memcached CRD and CR 
6. Apply operator.yaml , role.yaml, role_binding.yaml,  service_account.yaml 

Also, I'd recommend applying all in the same namespace. 

To troubleshooting:

- Check the pods and its logs (`kubectl get pod` and `kubectl logs <pod-name>`)
- Also, you are able to check them by the ui/cluster console. If it is OCP check the events tab in the pod. 

Please, let me know if with the above info and by following the PR changes you were able to make it works.

**Comment by skckadiyala** [comment] 2019-09-09 16:58
Thanks @camilamacedo86 , the issue is resolved in my environment with the instructions in the PR.

**Closed** 2019-09-24 17:16 UTC
Labels: kind/documentation, triage/support

**Comment by christianhxc** [comment] 2020-05-13 15:40
@camilamacedo86 I'm having the same problem using the operator sdk v0.17.0 in an EKS cluster, I've recreated the cluster, started from scratch with the project, and no luck.

When I see the logs of the memcached operator pod, I see the following:

```
{"level":"info","ts":1589383835.9011614,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1589383835.9011846,"logger":"cmd","msg":"Go Version: go1.14.2"}
{"level":"info","ts":1589383835.9011924,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1589383835.9011998,"logger":"cmd","msg":"Version of operator-sdk: v0.17.0"}
{"level":"info","ts":1589383835.901354,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1589383836.2175784,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1589383836.2232208,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1589383836.5271149,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1589383836.5277941,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1589383837.161486,"logger":"metrics","msg":"Metrics Service object created","Service.Name":"memcached-operator-metrics","Service.Namespace":"default"}
{"level":"info","ts":1589383837.463712,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1589383837.4637368,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1589383837.463749,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1589383837.463958,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1589383837.4641104,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"memcached-controller","source":"kind source: /, Kind="}
E0513 15:30:37.465907       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1alpha1.Memcached: memcacheds.cache.example.com is forbidden: User "system:serviceaccount:default:memcached-operator" cannot list resource "memcacheds" in API group "cache.example.com" at the cluster scope
E0513 15:30:38.467957       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1alpha1.Memcached: memcacheds.cache.example.com is forbidden: User "system:serviceaccount:default:memcached-operator" cannot list resource "memcacheds" in API group "cache.example.com" at the cluster scope
E0513 15:30:39.470002       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1alpha1.Memcached: memcacheds.cache.example.com is forbidden: User "system:serviceaccount:default:memcached-operator" cannot list resource "memcacheds" in API group "cache.example.com" at the cluster scope
```
And, if I run the following command to verify the SA permissions, I get a "yes" answer:

```
$ kubectl auth can-i list memcacheds --as system:serviceaccount:default:memcached-operator
yes
```

I'm not sure what I'm doing wrong but it's not working for me.
